# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
env:
    - DJANGO="Django==2.0.7"
    - DJANGO="Django==3.0.2"

# command to install dependencies, e.g. pip install -r requirements.txt
install:
 - pip install $DJANGO
 - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: python -m pytest --cov=admin_reorder

# report coverage to coveralls.io
after_success: coveralls
